### PR TITLE
added case-sensitive search for bug #77 fix.

### PR DESCRIPTION
**Pull request by bazmecode**
can you please review and merge?

### CODE REVIEW

**Comment by mbos** [comment]
Thanks for contributing!

So why are you handling it with the visual basic operator and not for example like:

```
if (tmpFileInfo.Name.ToLower().Contains(searchtext.ToLower()))
```

I see no obvious advantage (ie performance or something) over adding the extra binaries by using visual basic.
The test looks good! And you're using ToLower() there too :-)

**Comment by bazmecode** [comment]
The following code won't match wildcard searches like _._
<code>if (tmpFileInfo.Name.ToLower().Contains(searchtext.ToLower()))</code>

The visual basic library helps us in doing pattern matching.
<link>http://www.henrikbrinch.dk/Blog/2012/02/14/Wildcard-matching-in-C</link>

Although, I agree, instead of using the visual basic library, we can use regex for pattern matching :-)

**Comment by mbos** [comment]
Ah ok you want to use wild cards, which is a good idea tbh :-)
My personal preference would be regex, the perfomance hit would be neglible (some intresting tests about that http://cc.davelozinski.com/c-sharp/fastest-way-to-check-if-a-string-occurs-within-a-string). 
Could you rewrite it to regex?

**Comment by bazmecode** [comment]
done.

**Comment by mbos** [comment]
Thanks mate

**Pull request merged**
